/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'content' : string,
  'createdAt' : Time,
}
export interface IncomeStats {
  'totalIncome' : bigint,
  'levelIncome' : bigint,
  'rankBonus' : bigint,
  'directReferral' : bigint,
  'binaryPair' : bigint,
}
export interface MobileUser {
  'userId' : string,
  'fullName' : string,
  'phone' : string,
  'password' : string,
  'sponsorCode' : string,
  'joinDate' : Time,
  'isActive' : boolean,
  'walletBalance' : bigint,
  'totalEarnings' : bigint,
}
export interface MobileUserPublic {
  'userId' : string,
  'fullName' : string,
  'phone' : string,
  'sponsorCode' : string,
  'joinDate' : Time,
  'isActive' : boolean,
  'walletBalance' : bigint,
  'totalEarnings' : bigint,
}
export interface Package {
  'id' : bigint,
  'name' : string,
  'benefits' : string,
  'price' : bigint,
}
export type Position = { 'left' : null } |
  { 'right' : null };
export type Rank = { 'bronze' : null } |
  { 'starter' : null } |
  { 'gold' : null } |
  { 'diamond' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type Time = bigint;
export interface Transaction {
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'userId' : Principal,
  'date' : Time,
  'amount' : bigint,
  'relatedUser' : [] | [Principal],
  'transactionId' : string,
}
export type TransactionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type TransactionType = { 'adjustment' : null } |
  { 'levelIncome' : null } |
  { 'directReferralBonus' : null } |
  { 'rankBonus' : null } |
  { 'withdrawal' : null } |
  { 'binaryCommission' : null };
export interface User {
  'username' : string,
  'joinDate' : Time,
  'userId' : Principal,
  'rightChild' : [] | [Principal],
  'rank' : Rank,
  'sponsorId' : Principal,
  'leftChild' : [] | [Principal],
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'leftVolume' : bigint,
  'phone' : string,
  'rightVolume' : bigint,
  'position' : Position,
  'sponsorCode' : [] | [string],
}
export interface UserProfile {
  'username' : string,
  'joinDate' : Time,
  'rank' : Rank,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'availableBalance' : bigint,
  'userId' : Principal,
  'totalEarnings' : bigint,
  'pendingBalance' : bigint,
  'withdrawnAmount' : bigint,
}
export interface WithdrawalRequest {
  'status' : TransactionStatus,
  'requestId' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'paymentDetails' : string,
  'processedDate' : [] | [Time],
  'amount' : bigint,
  'requestDate' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string], undefined>,
  'addPackage' : ActorMethod<[string, bigint, string], bigint>,
  'addTransaction' : ActorMethod<
    [Principal, bigint, TransactionType, [] | [Principal]],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBinaryPairIncome' : ActorMethod<[Principal, bigint], undefined>,
  'awardDirectReferralIncome' : ActorMethod<
    [Principal, bigint, [] | [Principal]],
    undefined
  >,
  'awardLevelIncome' : ActorMethod<
    [Principal, bigint, bigint, [] | [Principal]],
    undefined
  >,
  'createFirstAdmin' : ActorMethod<[], undefined>,
  'loginAsAdmin' : ActorMethod<[string], boolean>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllMobileUsers' : ActorMethod<[], Array<MobileUser>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalStats' : ActorMethod<
    [],
    { 'activeUsers' : bigint, 'totalPaidOut' : bigint, 'totalUsers' : bigint }
  >,
  'getIncomeStats' : ActorMethod<[Principal], IncomeStats>,
  'getMobileUserByPhone' : ActorMethod<[string], [] | [MobileUserPublic]>,
  'getMyIncomeStats' : ActorMethod<[], IncomeStats>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getMyWallet' : ActorMethod<[], [] | [Wallet]>,
  'getMyWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserWallet' : ActorMethod<[Principal], [] | [Wallet]>,
  'getWithdrawalRequests' : ActorMethod<
    [[] | [Principal]],
    Array<WithdrawalRequest>
  >,
  'isAdminConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lookupSponsorByCode' : ActorMethod<[string], [] | [Principal]>,
  'processWithdrawalRequest' : ActorMethod<[string, boolean], undefined>,
  'purchasePackage' : ActorMethod<[bigint], undefined>,
  'registerMobileUser' : ActorMethod<[string, string, string, string], string>,
  'registerUser' : ActorMethod<
    [string, string, string, string, Principal, Position, [] | [string]],
    Principal
  >,
  'requestWithdrawal' : ActorMethod<[bigint, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserActiveStatus' : ActorMethod<[Principal, boolean], undefined>,
  'updateUserRank' : ActorMethod<[Principal, Rank], undefined>,
  'verifyMobileLogin' : ActorMethod<[string, string], [] | [MobileUserPublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
