/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'adjustment' : IDL.Null,
  'levelIncome' : IDL.Null,
  'directReferralBonus' : IDL.Null,
  'rankBonus' : IDL.Null,
  'withdrawal' : IDL.Null,
  'binaryCommission' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
});
export const MobileUser = IDL.Record({
  'userId' : IDL.Text,
  'fullName' : IDL.Text,
  'phone' : IDL.Text,
  'password' : IDL.Text,
  'sponsorCode' : IDL.Text,
  'joinDate' : IDL.Int,
  'isActive' : IDL.Bool,
  'walletBalance' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const MobileUserPublic = IDL.Record({
  'userId' : IDL.Text,
  'fullName' : IDL.Text,
  'phone' : IDL.Text,
  'sponsorCode' : IDL.Text,
  'joinDate' : IDL.Int,
  'isActive' : IDL.Bool,
  'walletBalance' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'benefits' : IDL.Text,
  'price' : IDL.Nat,
});
export const Rank = IDL.Variant({
  'bronze' : IDL.Null,
  'starter' : IDL.Null,
  'gold' : IDL.Null,
  'diamond' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const Position = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
export const User = IDL.Record({
  'username' : IDL.Text,
  'joinDate' : Time,
  'userId' : IDL.Principal,
  'rightChild' : IDL.Opt(IDL.Principal),
  'rank' : Rank,
  'sponsorId' : IDL.Principal,
  'leftChild' : IDL.Opt(IDL.Principal),
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'leftVolume' : IDL.Nat,
  'phone' : IDL.Text,
  'rightVolume' : IDL.Nat,
  'position' : Position,
  'sponsorCode' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'joinDate' : Time,
  'rank' : Rank,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const IncomeStats = IDL.Record({
  'totalIncome' : IDL.Nat,
  'levelIncome' : IDL.Nat,
  'rankBonus' : IDL.Nat,
  'directReferral' : IDL.Nat,
  'binaryPair' : IDL.Nat,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Transaction = IDL.Record({
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'userId' : IDL.Principal,
  'date' : Time,
  'amount' : IDL.Nat,
  'relatedUser' : IDL.Opt(IDL.Principal),
  'transactionId' : IDL.Text,
});
export const Wallet = IDL.Record({
  'availableBalance' : IDL.Nat,
  'userId' : IDL.Principal,
  'totalEarnings' : IDL.Nat,
  'pendingBalance' : IDL.Nat,
  'withdrawnAmount' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'status' : TransactionStatus,
  'requestId' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'paymentDetails' : IDL.Text,
  'processedDate' : IDL.Opt(Time),
  'amount' : IDL.Nat,
  'requestDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat, TransactionType, IDL.Opt(IDL.Principal)],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBinaryPairIncome' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'awardDirectReferralIncome' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'awardLevelIncome' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'createFirstAdmin' : IDL.Func([], [], []),
  'loginAsAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllMobileUsers' : IDL.Func([], [IDL.Vec(MobileUser)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeUsers' : IDL.Nat,
          'totalPaidOut' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getIncomeStats' : IDL.Func([IDL.Principal], [IncomeStats], ['query']),
  'getMobileUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(MobileUserPublic)], ['query']),
  'getMyIncomeStats' : IDL.Func([], [IncomeStats], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getMyWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
  'getWithdrawalRequests' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'isAdminConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lookupSponsorByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'processWithdrawalRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'purchasePackage' : IDL.Func([IDL.Nat], [], []),
  'registerMobileUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        Position,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Principal],
      [],
    ),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserActiveStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateUserRank' : IDL.Func([IDL.Principal, Rank], [], []),
  'verifyMobileLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(MobileUserPublic)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'adjustment' : IDL.Null,
    'levelIncome' : IDL.Null,
    'directReferralBonus' : IDL.Null,
    'rankBonus' : IDL.Null,
    'withdrawal' : IDL.Null,
    'binaryCommission' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  const MobileUser = IDL.Record({
    'userId' : IDL.Text,
    'fullName' : IDL.Text,
    'phone' : IDL.Text,
    'password' : IDL.Text,
    'sponsorCode' : IDL.Text,
    'joinDate' : IDL.Int,
    'isActive' : IDL.Bool,
    'walletBalance' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const MobileUserPublic = IDL.Record({
    'userId' : IDL.Text,
    'fullName' : IDL.Text,
    'phone' : IDL.Text,
    'sponsorCode' : IDL.Text,
    'joinDate' : IDL.Int,
    'isActive' : IDL.Bool,
    'walletBalance' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'benefits' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Rank = IDL.Variant({
    'bronze' : IDL.Null,
    'starter' : IDL.Null,
    'gold' : IDL.Null,
    'diamond' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const Position = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
  const User = IDL.Record({
    'username' : IDL.Text,
    'joinDate' : Time,
    'userId' : IDL.Principal,
    'rightChild' : IDL.Opt(IDL.Principal),
    'rank' : Rank,
    'sponsorId' : IDL.Principal,
    'leftChild' : IDL.Opt(IDL.Principal),
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'leftVolume' : IDL.Nat,
    'phone' : IDL.Text,
    'rightVolume' : IDL.Nat,
    'position' : Position,
    'sponsorCode' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'joinDate' : Time,
    'rank' : Rank,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const IncomeStats = IDL.Record({
    'totalIncome' : IDL.Nat,
    'levelIncome' : IDL.Nat,
    'rankBonus' : IDL.Nat,
    'directReferral' : IDL.Nat,
    'binaryPair' : IDL.Nat,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'userId' : IDL.Principal,
    'date' : Time,
    'amount' : IDL.Nat,
    'relatedUser' : IDL.Opt(IDL.Principal),
    'transactionId' : IDL.Text,
  });
  const Wallet = IDL.Record({
    'availableBalance' : IDL.Nat,
    'userId' : IDL.Principal,
    'totalEarnings' : IDL.Nat,
    'pendingBalance' : IDL.Nat,
    'withdrawnAmount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : TransactionStatus,
    'requestId' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'paymentDetails' : IDL.Text,
    'processedDate' : IDL.Opt(Time),
    'amount' : IDL.Nat,
    'requestDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, TransactionType, IDL.Opt(IDL.Principal)],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBinaryPairIncome' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'awardDirectReferralIncome' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'awardLevelIncome' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'createFirstAdmin' : IDL.Func([], [], []),
    'loginAsAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllMobileUsers' : IDL.Func([], [IDL.Vec(MobileUser)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeUsers' : IDL.Nat,
            'totalPaidOut' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getIncomeStats' : IDL.Func([IDL.Principal], [IncomeStats], ['query']),
    'getMobileUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(MobileUserPublic)], ['query']),
    'getMyIncomeStats' : IDL.Func([], [IncomeStats], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getMyWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
    'getWithdrawalRequests' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isAdminConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lookupSponsorByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'processWithdrawalRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'purchasePackage' : IDL.Func([IDL.Nat], [], []),
    'registerMobileUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          Position,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Principal],
        [],
      ),
    'requestWithdrawal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserActiveStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateUserRank' : IDL.Func([IDL.Principal, Rank], [], []),
    'verifyMobileLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(MobileUserPublic)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
