/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface User {
    username: string;
    joinDate: Time;
    userId: Principal;
    rightChild?: Principal;
    rank: Rank;
    sponsorId: Principal;
    leftChild?: Principal;
    fullName: string;
    isActive: boolean;
    email: string;
    leftVolume: bigint;
    phone: string;
    rightVolume: bigint;
    position: Position;
    sponsorCode?: string;
}
export interface IncomeStats {
    totalIncome: bigint;
    levelIncome: bigint;
    rankBonus: bigint;
    directReferral: bigint;
    binaryPair: bigint;
}
export interface Package {
    id: bigint;
    name: string;
    benefits: string;
    price: bigint;
}
export interface Transaction {
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: Principal;
    date: Time;
    amount: bigint;
    relatedUser?: Principal;
    transactionId: string;
}
export interface Wallet {
    availableBalance: bigint;
    userId: Principal;
    totalEarnings: bigint;
    pendingBalance: bigint;
    withdrawnAmount: bigint;
}
export interface Announcement {
    title: string;
    content: string;
    createdAt: Time;
}
export interface WithdrawalRequest {
    status: TransactionStatus;
    requestId: string;
    paymentMethod: string;
    userId: Principal;
    paymentDetails: string;
    processedDate?: Time;
    amount: bigint;
    requestDate: Time;
}
export interface UserProfile {
    username: string;
    joinDate: Time;
    rank: Rank;
    fullName: string;
    isActive: boolean;
    email: string;
    phone: string;
}
export enum Position {
    left = "left",
    right = "right"
}
export enum Rank {
    bronze = "bronze",
    starter = "starter",
    gold = "gold",
    diamond = "diamond",
    platinum = "platinum",
    silver = "silver"
}
export enum TransactionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TransactionType {
    adjustment = "adjustment",
    levelIncome = "levelIncome",
    directReferralBonus = "directReferralBonus",
    rankBonus = "rankBonus",
    withdrawal = "withdrawal",
    binaryCommission = "binaryCommission"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(title: string, content: string): Promise<void>;
    addPackage(name: string, price: bigint, benefits: string): Promise<bigint>;
    addTransaction(userId: Principal, amount: bigint, transactionType: TransactionType, relatedUser: Principal | null): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardBinaryPairIncome(toUser: Principal, amount: bigint): Promise<void>;
    awardDirectReferralIncome(toUser: Principal, amount: bigint, fromUser: Principal | null): Promise<void>;
    awardLevelIncome(toUser: Principal, amount: bigint, level: bigint, fromUser: Principal | null): Promise<void>;
    createFirstAdmin(): Promise<void>;
    loginAsAdmin(password: string): Promise<boolean>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGlobalStats(): Promise<{
        activeUsers: bigint;
        totalPaidOut: bigint;
        totalUsers: bigint;
    }>;
    getIncomeStats(userId: Principal): Promise<IncomeStats>;
    getMyIncomeStats(): Promise<IncomeStats>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getMyWallet(): Promise<Wallet | null>;
    getMyWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getUser(userId: Principal): Promise<User | null>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    getUserTransactions(userId: Principal): Promise<Array<Transaction>>;
    getUserWallet(userId: Principal): Promise<Wallet | null>;
    getWithdrawalRequests(userId: Principal | null): Promise<Array<WithdrawalRequest>>;
    isAdminConfigured(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    lookupSponsorByCode(code: string): Promise<Principal | null>;
    processWithdrawalRequest(requestId: string, approve: boolean): Promise<void>;
    purchasePackage(packageId: bigint): Promise<void>;
    registerUser(username: string, fullName: string, email: string, phone: string, sponsorId: Principal, position: Position, sponsorCode: string | null): Promise<Principal>;
    registerMobileUser(fullName: string, phone: string, password: string, sponsorCode: string): Promise<string>;
    purchaseMobileUserPlan(phone: string, packageId: bigint): Promise<string>;
    upgradeMobileUserPlan(phone: string, newPlanId: bigint): Promise<string>;
    getMobileUserActivePlan(phone: string): Promise<[bigint] | []>;
    submitRechargeRequest(phone: string, amount: bigint, method: 'upi' | 'bank', upiId: string, utrNumber: string, bankName: string): Promise<string>;
    getRechargeRequests(): Promise<Array<RechargeRequest>>;
    getMyRechargeRequests(phone: string): Promise<Array<RechargeRequest>>;
    approveRechargeRequest(requestId: string, adminNote: string): Promise<void>;
    rejectRechargeRequest(requestId: string, adminNote: string): Promise<void>;
    adminCreditWallet(phone: string, amount: bigint, note: string): Promise<void>;

    requestWithdrawal(amount: bigint, paymentMethod: string, paymentDetails: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserActiveStatus(userId: Principal, isActive: boolean): Promise<void>;
    sendOtpToPhone(phone: string): Promise<string>;
    verifyPhoneOtp(phone: string, otp: string): Promise<boolean>;
    setMsg91Config(authKey: string, templateId: string, senderId: string): Promise<void>;
    getMsg91Config(): Promise<{ configured: boolean; templateId: string; senderId: string }>;
    updateUserRank(userId: Principal, newRank: Rank): Promise<void>;
}
import type { Position as _Position, Rank as _Rank, Time as _Time, Transaction as _Transaction, TransactionStatus as _TransactionStatus, TransactionType as _TransactionType, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, Wallet as _Wallet, WithdrawalRequest as _WithdrawalRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1);
            return result;
        }
    }
    async addPackage(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackage(arg0, arg1, arg2);
            return result;
        }
    }
    async addTransaction(arg0: Principal, arg1: bigint, arg2: TransactionType, arg3: Principal | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardBinaryPairIncome(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBinaryPairIncome(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBinaryPairIncome(arg0, arg1);
            return result;
        }
    }
    async awardDirectReferralIncome(arg0: Principal, arg1: bigint, arg2: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardDirectReferralIncome(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardDirectReferralIncome(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async awardLevelIncome(arg0: Principal, arg1: bigint, arg2: bigint, arg3: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardLevelIncome(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardLevelIncome(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createFirstAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFirstAdmin();
            return result;
        }
    }
    async loginAsAdmin(password: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginAsAdmin(password);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginAsAdmin(password);
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalStats(): Promise<{
        activeUsers: bigint;
        totalPaidOut: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalStats();
            return result;
        }
    }
    async getIncomeStats(arg0: Principal): Promise<IncomeStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeStats(arg0);
            return result;
        }
    }
    async getMyIncomeStats(): Promise<IncomeStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyIncomeStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyIncomeStats();
            return result;
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWallet(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWallet();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWallet();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWithdrawalRequests();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWithdrawalRequests();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactions(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWallet(arg0: Principal): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWallet(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWallet(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequests(arg0: Principal | null): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminConfigured();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async lookupSponsorByCode(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupSponsorByCode(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupSponsorByCode(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async processWithdrawalRequest(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async purchasePackage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePackage(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Principal, arg5: Position, arg6: string | null): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, to_candid_Position_n33(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, to_candid_Position_n33(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async registerMobileUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMobileUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMobileUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async purchaseMobileUserPlan(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseMobileUserPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseMobileUserPlan(arg0, arg1);
            return result;
        }
    }
    async upgradeMobileUserPlan(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeMobileUserPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeMobileUserPlan(arg0, arg1);
            return result;
        }
    }
    async getMobileUserActivePlan(arg0: string): Promise<[bigint] | []> {
        if (this.processError) {
            try {
                const result = await this.actor.getMobileUserActivePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMobileUserActivePlan(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserActiveStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserActiveStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserActiveStatus(arg0, arg1);
            return result;
        }
    }
    async updateUserRank(arg0: Principal, arg1: Rank): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRank(arg0, to_candid_Rank_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRank(arg0, to_candid_Rank_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }


    async submitRechargeRequest(phone: string, amount: bigint, method: 'upi' | 'bank', upiId: string, utrNumber: string, bankName: string): Promise<string> {
        const methodVariant = method === 'upi' ? { upi: null } : { bank: null };
        try {
            if (this.processError) {
                try { return await this.actor.submitRechargeRequest(phone, amount, methodVariant, upiId, utrNumber, bankName); }
                catch(e) { this.processError(e); }
            }
            return await this.actor.submitRechargeRequest(phone, amount, methodVariant, upiId, utrNumber, bankName);
        } catch(e) { throw e; }
    }

    async getRechargeRequests(): Promise<Array<RechargeRequest>> {
        try {
            const results = await this.actor.getRechargeRequests();
            return results.map((r: any) => ({
                ...r,
                method: 'upi' in r.method ? RechargeMethod.upi : RechargeMethod.bank,
                status: 'pending' in r.status ? RechargeStatus.pending : 'approved' in r.status ? RechargeStatus.approved : RechargeStatus.rejected,
                processedDate: r.processedDate.length > 0 ? r.processedDate[0] : null,
            }));
        } catch(e) { throw e; }
    }

    async getMyRechargeRequests(phone: string): Promise<Array<RechargeRequest>> {
        try {
            const results = await this.actor.getMyRechargeRequests(phone);
            return results.map((r: any) => ({
                ...r,
                method: 'upi' in r.method ? RechargeMethod.upi : RechargeMethod.bank,
                status: 'pending' in r.status ? RechargeStatus.pending : 'approved' in r.status ? RechargeStatus.approved : RechargeStatus.rejected,
                processedDate: r.processedDate.length > 0 ? r.processedDate[0] : null,
            }));
        } catch(e) { throw e; }
    }

    async approveRechargeRequest(requestId: string, adminNote: string): Promise<void> {
        try {
            if (this.processError) {
                try { return await this.actor.approveRechargeRequest(requestId, adminNote); }
                catch(e) { this.processError(e); }
            }
            return await this.actor.approveRechargeRequest(requestId, adminNote);
        } catch(e) { throw e; }
    }

    async rejectRechargeRequest(requestId: string, adminNote: string): Promise<void> {
        try {
            if (this.processError) {
                try { return await this.actor.rejectRechargeRequest(requestId, adminNote); }
                catch(e) { this.processError(e); }
            }
            return await this.actor.rejectRechargeRequest(requestId, adminNote);
        } catch(e) { throw e; }
    }

    async adminCreditWallet(phone: string, amount: bigint, note: string): Promise<void> {
        try {
            if (this.processError) {
                try { return await this.actor.adminCreditWallet(phone, amount, note); }
                catch(e) { this.processError(e); }
            }
            return await this.actor.adminCreditWallet(phone, amount, note);
        } catch(e) { throw e; }
    }
    async sendOtpToPhone(phone: string): Promise<string> {
        if (this.processError) {
            try { return await this.actor.sendOtpToPhone(phone); }
            catch(e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.sendOtpToPhone(phone);
    }
    async verifyPhoneOtp(phone: string, otp: string): Promise<boolean> {
        if (this.processError) {
            try { return await this.actor.verifyPhoneOtp(phone, otp); }
            catch(e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.verifyPhoneOtp(phone, otp);
    }
    async setMsg91Config(authKey: string, templateId: string, senderId: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.setMsg91Config(authKey, templateId, senderId); }
            catch(e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.setMsg91Config(authKey, templateId, senderId);
    }
    async getMsg91Config(): Promise<{ configured: boolean; templateId: string; senderId: string }> {
        if (this.processError) {
            try {
                const r = await this.actor.getMsg91Config();
                return { configured: Boolean(r.configured), templateId: String(r.templateId), senderId: String(r.senderId) };
            }
            catch(e) { this.processError(e); throw new Error("unreachable"); }
        }
        const r = await this.actor.getMsg91Config();
        return { configured: Boolean(r.configured), templateId: String(r.templateId), senderId: String(r.senderId) };
    }

}
function from_candid_Position_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Rank_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rank): Rank {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_User_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    joinDate: _Time;
    rank: _Rank;
    fullName: string;
    isActive: boolean;
    email: string;
    phone: string;
}): {
    username: string;
    joinDate: Time;
    rank: Rank;
    fullName: string;
    isActive: boolean;
    email: string;
    phone: string;
} {
    return {
        username: value.username,
        joinDate: value.joinDate,
        rank: from_candid_Rank_n10(_uploadFile, _downloadFile, value.rank),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransactionStatus;
    transactionType: _TransactionType;
    userId: Principal;
    date: _Time;
    amount: bigint;
    relatedUser: [] | [Principal];
    transactionId: string;
}): {
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: Principal;
    date: Time;
    amount: bigint;
    relatedUser?: Principal;
    transactionId: string;
} {
    return {
        status: from_candid_TransactionStatus_n23(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_TransactionType_n25(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        date: value.date,
        amount: value.amount,
        relatedUser: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.relatedUser)),
        transactionId: value.transactionId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransactionStatus;
    requestId: string;
    paymentMethod: string;
    userId: Principal;
    paymentDetails: string;
    processedDate: [] | [_Time];
    amount: bigint;
    requestDate: _Time;
}): {
    status: TransactionStatus;
    requestId: string;
    paymentMethod: string;
    userId: Principal;
    paymentDetails: string;
    processedDate?: Time;
    amount: bigint;
    requestDate: Time;
} {
    return {
        status: from_candid_TransactionStatus_n23(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        paymentMethod: value.paymentMethod,
        userId: value.userId,
        paymentDetails: value.paymentDetails,
        processedDate: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.processedDate)),
        amount: value.amount,
        requestDate: value.requestDate
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    joinDate: _Time;
    userId: Principal;
    rightChild: [] | [Principal];
    rank: _Rank;
    sponsorId: Principal;
    leftChild: [] | [Principal];
    fullName: string;
    isActive: boolean;
    email: string;
    leftVolume: bigint;
    phone: string;
    rightVolume: bigint;
    position: _Position;
    sponsorCode: [] | [string];
}): {
    username: string;
    joinDate: Time;
    userId: Principal;
    rightChild?: Principal;
    rank: Rank;
    sponsorId: Principal;
    leftChild?: Principal;
    fullName: string;
    isActive: boolean;
    email: string;
    leftVolume: bigint;
    phone: string;
    rightVolume: bigint;
    position: Position;
    sponsorCode?: string;
} {
    return {
        username: value.username,
        joinDate: value.joinDate,
        userId: value.userId,
        rightChild: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.rightChild)),
        rank: from_candid_Rank_n10(_uploadFile, _downloadFile, value.rank),
        sponsorId: value.sponsorId,
        leftChild: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.leftChild)),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        leftVolume: value.leftVolume,
        phone: value.phone,
        rightVolume: value.rightVolume,
        position: from_candid_Position_n12(_uploadFile, _downloadFile, value.position),
        sponsorCode: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.sponsorCode))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    starter: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
}): Rank {
    return "bronze" in value ? Rank.bronze : "starter" in value ? Rank.starter : "gold" in value ? Rank.gold : "diamond" in value ? Rank.diamond : "platinum" in value ? Rank.platinum : "silver" in value ? Rank.silver : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    left: null;
} | {
    right: null;
}): Position {
    return "left" in value ? Position.left : "right" in value ? Position.right : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "approved" in value ? TransactionStatus.approved : "rejected" in value ? TransactionStatus.rejected : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: null;
} | {
    levelIncome: null;
} | {
    directReferralBonus: null;
} | {
    rankBonus: null;
} | {
    withdrawal: null;
} | {
    binaryCommission: null;
}): TransactionType {
    return "adjustment" in value ? TransactionType.adjustment : "levelIncome" in value ? TransactionType.levelIncome : "directReferralBonus" in value ? TransactionType.directReferralBonus : "rankBonus" in value ? TransactionType.rankBonus : "withdrawal" in value ? TransactionType.withdrawal : "binaryCommission" in value ? TransactionType.binaryCommission : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Position_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Rank_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rank): _Rank {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    joinDate: Time;
    rank: Rank;
    fullName: string;
    isActive: boolean;
    email: string;
    phone: string;
}): {
    username: string;
    joinDate: _Time;
    rank: _Rank;
    fullName: string;
    isActive: boolean;
    email: string;
    phone: string;
} {
    return {
        username: value.username,
        joinDate: value.joinDate,
        rank: to_candid_Rank_n38(_uploadFile, _downloadFile, value.rank),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    adjustment: null;
} | {
    levelIncome: null;
} | {
    directReferralBonus: null;
} | {
    rankBonus: null;
} | {
    withdrawal: null;
} | {
    binaryCommission: null;
} {
    return value == TransactionType.adjustment ? {
        adjustment: null
    } : value == TransactionType.levelIncome ? {
        levelIncome: null
    } : value == TransactionType.directReferralBonus ? {
        directReferralBonus: null
    } : value == TransactionType.rankBonus ? {
        rankBonus: null
    } : value == TransactionType.withdrawal ? {
        withdrawal: null
    } : value == TransactionType.binaryCommission ? {
        binaryCommission: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): {
    left: null;
} | {
    right: null;
} {
    return value == Position.left ? {
        left: null
    } : value == Position.right ? {
        right: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rank): {
    bronze: null;
} | {
    starter: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
} {
    return value == Rank.bronze ? {
        bronze: null
    } : value == Rank.starter ? {
        starter: null
    } : value == Rank.gold ? {
        gold: null
    } : value == Rank.diamond ? {
        diamond: null
    } : value == Rank.platinum ? {
        platinum: null
    } : value == Rank.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}

export enum RechargeMethod { upi = "upi", bank = "bank" }
export enum RechargeStatus { pending = "pending", approved = "approved", rejected = "rejected" }
export interface RechargeRequest {
    requestId: string;
    phone: string;
    amount: bigint;
    method: RechargeMethod;
    upiId: string;
    utrNumber: string;
    bankName: string;
    status: RechargeStatus;
    requestDate: bigint;
    processedDate: bigint | null;
    adminNote: string;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
